### ISSUE TITLE
Does this library has built in capability to have offline first approach same as 'sync-Android' ?

### ISSUE THREAD

**Issue by ZaheerUdDeen** [cloudant/xamarin-cloudant#53]
I want to know the following information.
- does xamarin-cloudant has the capability(offline first) that [sync-android](https://github.com/cloudant/sync-android/blob/master/doc/query.md) has?
-  If not, is there any chances to have this feature in future?
- if it has, please referred me to the materials.

**Comment by tomblench** [comment]
To answer your questions, in order:

- No
- This is not planned on any current roadmap
- Not applicable
